[env:esp32-2424S012C]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600

build_flags = 
    -DESP32_2424S012C
    -DBOARD_HAS_PSRAM=0
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1

lib_deps = 
    lovyan03/LovyanGFX@^1.1.16
    bblanchon/ArduinoJson@^7.0.4
    fbiego/CST816S@^1.1.1
